---
title: "Mixed Effects Model tutorial From Coding Club Gabriela K Hajduk (2019)  "
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: cerulean
    highlight: haddock
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC
Title: Mixed Effects Model Tutorial
Date: 2021 (R document January 2021)


Original Tutorial Offered at: 
[Coding Club Tutorial](https://ourcodingclub.github.io/tutorials/mixed-models/#what)


1. What is mixed effects modelling and why does it matter?
Ecological and biological data are often complex and messy.     - TRUE
We can have different grouping factors like populations, 
        species, 
        sites where we collect the data, etc.                   - TRUE
        

Sample sizes might leave something to be desired too, 
        especially if we are trying to fit complicated 
        models with many parameters. 

On top of that, our data points might not be truly independent. 
For instance, we might be using quadrats within our 
        sites to collect the data (and so there is structure 
        to our data: quadrats are nested within the sites)

This is why mixed models were developed, 
        to deal with such messy data and to allow us to use all our data, 
        even when we have low sample sizes, 
        structured data and many covariates to fit. 


Oh, and on top of all that, mixed models allow us to save degrees of freedom compared to running standard linear models! Sounds good, doesn’t it?

We will cover only linear mixed models here, but if you are trying to “extend” your linear model, fear not: there are generalised linear mixed effects models out there, too.


 





















